function parameters = import_parameter(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PARAMETERS234 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  PARAMETERS234 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  parameters234 = importfile("C:\Users\kimwo\MATLAB Drive\Workspace\SPPALs\parameters\parameters_234.txt", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2023-01-20 17:08:02

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["e_", "l", "r","Mat"];
% opts.SelectedVariableNames = ["Length", "Radius","Material"];
opts.VariableTypes = ["double", "double", "double", "string"];
opts.VariableUnitsLine = 2;
% opts.RowNamesColumn = 1;

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
parameters = readtable(filename, opts);
A    = pi*parameters.r.^2;
parameters = addvars(parameters, A,'After','r');
parameters.Properties.VariableUnits(4) = "m";

end