function materials = import_material(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ALUMINUM = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  ALUMINUM = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  aluminum = importfile("C:\Users\kimwo\MATLAB Drive\Workspace\SPPALs\materials\aluminum.txt", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2023-01-08 15:25:47

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Mat", "rho", "Y33", "nu","eps33","d33","d31","DF"];
% opts.SelectedVariableNames = ["Density", "YoungsModulus", "PoissonRatio","eps33","d33","d31","DissipationFactor"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double"];
opts.VariableUnitsLine = 2;
opts.RowNamesColumn = 1;

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Mat", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Mat", "EmptyFieldRule", "auto");

% Import the data
materials = readtable(filename, opts);
v3 = sqrt(materials.Y33./materials.rho);
materials = addvars(materials,v3);
materials.Properties.VariableUnits(9) = "m/s";

end